version: '3.4'

services:
  spacecards.api:
    image: ${DOCKER_REGISTRY-}spacecardsapi
    build:
      context: .
      dockerfile: SpaceCards.API/Dockerfile
    container_name: api 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
      - 5433:5432
    container_name: db  

