version: '3.4'

services:
  spacecards.api:
    image: ${DOCKER_REGISTRY-}spacecardsapi
    build:
      context: .
      dockerfile: SpaceCards.API/Dockerfile
    container_name: api 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
      - 5433:5432
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 14269:14269
      - 16686:16686

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 5340:80
 
volumes:
  db-data:
    driver: local

