name: .NET

on:
  push:
    branches: [main]
    paths-ignore:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore backend/SpaceCards.sln
      - name: Build
        run: dotnet build backend/SpaceCards.sln --no-restore

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: dotnet test backend/SpaceCards.UnitTests/SpaceCards.UnitTests.csproj --verbosity normal

  integretion_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0

        with:
          postgresql db: SpaceCardsDb
          postgresql password: pwd

      - name: Init secrets API
        run: dotnet user-secrets init -p backend/SpaceCards.API 
       
      - name: Set connection string API
        run: dotnet user-secrets set "ConnectionStrings:SpaceCardsDb" "User ID=postgres;Password=pwd;Host=localhost;Port=5432;Database=SpaceCardsDb;Pooling=true;" -p backend/SpaceCards.API 
       
      - name: Set MailRu client secret
        run: dotnet user-secrets set "ExternalAuthenticationOptions:MailRu:ClientSecret" ${{ secrets.CLIENTSECRET }}

      - name: Set MailRu client id
        run: dotnet user-secrets set "ExternalAuthenticationOptions:MailRu:ClientId" ${{ secrets.CLIENTID }}

      - name: Set Google client id
        run: dotnet user-secrets set "ExternalAuthenticationOptions:Google:ClientId" ${{ secrets.CLIENTIDGOOGLE }}

      - name: Set Google client secret
        run: dotnet user-secrets set "ExternalAuthenticationOptions:Google:ClientSecret" ${{ secrets.CLIENTSECRETGOOGLE }}
        
      - name: Init secrets Integration Tests
        run: dotnet user-secrets init -p backend/SpaceCards.IntegrationTests 

      - name: Set connection string IntegrationalTests
        run: dotnet user-secrets set "ConnectionStrings:SpaceCardsDb" "User ID=postgres;Password=pwd;Host=localhost;Port=5432;Database=SpaceCardsDb;Pooling=true;" -p backend/SpaceCards.IntegrationTests
      
      - name: tool restore
        run: dotnet tool restore --tool-manifest .config/dotnet-tools.json

      - name: update database
        run: dotnet ef database update -p backend/SpaceCards.DataAccess.Postgre -s backend/SpaceCards.API 
        
      - name: Test
        run: dotnet test backend/SpaceCards.IntegrationTests/SpaceCards.IntegrationTests.csproj --verbosity normal /p:ParallelizeTestCollections=false
